version: 2

env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/zexot-com/commitlint/internal.version=v{{.Major}}.{{.Minor}}.{{.Patch}} -X github.com/zexot-com/commitlint/internal.commit={{.FullCommit}} -X github.com/zexot-com/commitlint/internal.buildTime={{.Date}}
    flags:
      - -tags=urfave_cli_no_docs

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - LICENSE.md
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^style:"
      - "^chore:"
      - "^refactor:"
      - "^build:"
      - "^ci:"

release:
  draft: true
