name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-15]
        version: [1.21.0, 1.23.0]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5.3.0
        with:
          go-version: ${{ matrix.version }}
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6.2.1
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        uses: actions/upload-artifact@v4.6.1
        with:
          name: binary-${{ matrix.os }}-${{ matrix.version }}
          path: binary
